// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPjriAj1rqFv0HobhZ11DWPvM1Zla7BgY',
    appId: '1:160888612832:web:02fafdcbb5d28cca886d85',
    messagingSenderId: '160888612832',
    projectId: 'first-c4a1a',
    authDomain: 'first-c4a1a.firebaseapp.com',
    storageBucket: 'first-c4a1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpWHBrRy0zTA487mLk_vHB-PF5Tc2DLI',
    appId: '1:160888612832:android:e7b10e1cbd6367b8886d85',
    messagingSenderId: '160888612832',
    projectId: 'first-c4a1a',
    storageBucket: 'first-c4a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD007DaFyf7JV0eZQSOetQ7wMduhDw928M',
    appId: '1:160888612832:ios:67ea1e2a0a3ad2ec886d85',
    messagingSenderId: '160888612832',
    projectId: 'first-c4a1a',
    storageBucket: 'first-c4a1a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD007DaFyf7JV0eZQSOetQ7wMduhDw928M',
    appId: '1:160888612832:ios:0e2bf41aa78029dd886d85',
    messagingSenderId: '160888612832',
    projectId: 'first-c4a1a',
    storageBucket: 'first-c4a1a.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
